<a href="https://colab.research.google.com/github/Plusholic/Engineer_BigDataAnalysis/blob/main/BigData_exercise_type_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!git clone https://github.com/AnalyticsKnight/yemoonsaBigdata/

Cloning into 'yemoonsaBigdata'...
remote: Enumerating objects: 485, done.
remote: Counting objects: 100% (122/122), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 485 (delta 66), reused 49 (delta 44), pack-reused 363
Receiving objects: 100% (485/485), 8.89 MiB | 10.46 MiB/s, done.
Resolving deltas: 100% (251/251), done.

In [96]:
import pandas as pd
import numpy as np

# 1유형 1번문제
data = pd.read_csv("/content/yemoonsaBigdata/datasets/Part2/iris.csv")

# 1유형 1-1
a = data['petal_width'][data['species'] == 'setosa'].quantile(0.75)
b = data['petal_width'][data['species'] == 'virginica'].quantile(0.75)
c = data['petal_width'][data['species'] == 'versicolor'].quantile(0.75)
print(max([a,b,c]))
print(min([a,b,c]))

# 아 이거 조심해야할듯 정리필수. print 해 본 다음에 직접 뺄것.
print('1번 답 : ', max([a,b,c]) - min([a,b,c])) 

# 1유형 1-2

d = data['sepal_length'].value_counts().keys().tolist()
d.sort() # list 오름차순 정렬
print('2번 답 : ', d[9]) # 10번째 오는 숫자

# 1유형 1-3
reverse=False
idx = data['sepal_width'].sort_values(ascending=False).index[:100]
train_data = data.loc[idx]
print('3번 답 : ', int(np.std(train_data['sepal_width'])*50)) #소수점 이하 값은 버림

# 1유형 1-4
a = data['petal_length'][data['species'] == 'setosa'].sort_values(ascending=False)
b = data['petal_length'][data['species'] == 'virginica'].sort_values(ascending=False)
c = data['petal_length'][data['species'] == 'versicolor'].sort_values(ascending=False)
print('4번 답 : ', round(a[:10].mean() + b[:10].mean() + c[:10].mean()))

# 1유형 1-5
data['sepal_length'].describe()
lb = data['sepal_length'].mean() - 2 * data['sepal_length'].std()
ub = data['sepal_length'].mean() + 2 * data['sepal_length'].std()
print('5번 답 : ', len(data[(data['sepal_length'] >= ub) | (data['sepal_length'] <= lb)]))

print(' ')
# 1유형 2번문제

from sklearn.impute import SimpleImputer

data2 = pd.read_csv("/content/yemoonsaBigdata/datasets/Part2/wine.csv")

data_1 = data2.copy()
# alcalinity_of_ash 결측치 중앙값 대체
imputer = SimpleImputer(strategy='median')
data_1[['alcalinity_of_ash']] = imputer.fit_transform(data_1[['alcalinity_of_ash']])
# total_phenols  결측치 제거
data_1.dropna(subset=['total_phenols'], inplace=True) # subset 옵션을 지정해줘서 특정 행의 결측치 기준으로 제거해줄수 있음
print('1번 답 : ', int(data_1[['alcalinity_of_ash']].mean()))

# 2-2번
data_2 = data2.copy()
data_2['class'][(data_2['alcohol'] >= data_2['alcohol'].mean()) & (data_2['color_intensity'] >= data_2['color_intensity'].mean())].value_counts()
print('2번 답 : ',0)

# 2-3번
data_3 = data2.copy()
a = data_3['ash'][data_3['class'] == 1].mean()
data_3.dropna(inplace=True)
b = data_3['ash'].mean()
print('3번 답 : ', round(abs(a-b),3))

# 2-4번 #?? 왜이래
data_4 = data2.copy()
# alcohol 변수의 상위 20번째 값으로 상위 20개 값 변환
data_4.sort_values(by='alcohol',ascending=True, inplace=True)
data_4.loc[:19,'alcohol'] = data_4.loc[19,'alcohol']
# proanthocyanins가 2 이하인 데이터를 추출하여 alcohol의 평균값 계산
c = data_4['alcohol'][data_4['proanthocyanins'] <= 2].mean()
print(data_4.head(25))
print('4번 답 : ', round(c,2))

# 책 답
data_4 = data2.copy()
data_sorted = data_4.sort_values(by='alcohol')
data_sorted.loc[0:19,'alcohol'] = data_sorted.loc[19,'alcohol']
print(data_sorted.head(22))

# 2-5번

data_5 = data2.copy()

# class 1에서 proline의 3사분위수 - 1사분위수
d = data_5['proline'][data_5['class'] == 1].quantile(1/4) - data_5['proline'][data_5['class'] == 1].quantile(3/4)
# class 2에서 proline의 3사분위수 - 1사분위수
e = data_5['proline'][data_5['class'] == 2].quantile(1/4) - data_5['proline'][data_5['class'] == 2].quantile(3/4)
print('5번 답 : ', abs(d-e))

2.3
0.3
1번 답 :  1.9999999999999998
2번 답 :  5.2
3번 답 :  16
4번 답 :  13
5번 답 :  6

1번 답 :  19
2번 답 :  0
3번 답 :  0.12
     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
115    13.64        1.51  2.20                NaN       85.0           2.46
113    13.64        0.74  2.50               21.0       88.0           2.48
120    13.64        2.40  2.42               20.0       96.0           2.90
110    13.64        3.74  1.82               19.5      107.0           3.18
121    13.64        2.05  3.23               28.5      119.0            NaN
109    13.64        1.35  2.70               20.0       94.0           2.74
94     13.64        1.99  2.28               18.0       98.0           3.02
88     13.64        2.06  2.46               21.6       84.0           1.95
87     13.64        1.67  2.62               26.0       88.0           1.92
75     13.64        1.88  1.92               16.0       97.0           1.61
112    13.64        2.68  2.92               20.0      103.0           1.75
127    13.64        2.13  2.78               28.5       92.0           2.13
96     13.64        2.12  2.74               21.5      134.0           1.60
103    13.64        1.72  1.88               19.5       86.0           2.50
116    13.64        1.47  1.99               20.8       86.0           1.98
84     13.64        0.89  2.58               18.0       94.0           2.20
77     13.64        2.89  2.23               18.0      112.0           1.72
124    13.64        4.31  2.39               21.0       82.0           2.86
74     13.64        1.09  2.30               21.0      101.0           3.38
119    13.64        3.43  2.00               19.0       87.0           2.00
91     13.64        1.51  2.42               22.0       86.0           1.45
80     13.64        0.92  2.00               19.0       86.0           2.42
129    13.64        4.30  2.38               22.0       80.0           2.10
125    13.64        2.16  2.17               21.0       85.0           2.60
82     13.64        1.13  2.51               24.0       78.0           2.00

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
115        2.17                  0.52             2.01             1.90  1.71
113        2.01                  0.42             1.44             3.08  1.10
120        2.79                  0.32             1.83             3.25  0.80
110        2.58                  0.24             3.58             2.90  0.75
121        5.08                  0.47             1.87             6.00  0.93
109        2.92                  0.29             2.49             2.65  0.96
94         2.26                  0.17             1.35             3.25  1.16
88         1.69                  0.48             1.35             2.80  1.00
87         1.61                  0.40             1.34             2.60  1.36
75         1.57                  0.34             1.15             3.80  1.23
112        2.03                  0.60             1.05             3.80  1.23
127        2.24                  0.58             1.76             3.00  0.97
96         0.99                  0.14             1.56             2.50  0.95
103        1.64                  0.37             1.42             2.06  0.94
116        1.60                  0.30             1.53             1.95  0.95
84         2.21                  0.22             2.35             3.05  0.79
77         1.32                  0.43             0.95             2.65  0.96
124        3.03                  0.21             2.91             2.80  0.75
74         2.14                  0.13             1.65             3.21  0.99
119        1.64                  0.37             1.87             1.28  0.93
91         1.25                  0.50             1.63             3.60  1.05
80         2.26                  0.30             1.43             2.50  1.38
129        1.75                  0.42             1.35             2.60  0.79
125        2.65                  0.37             1.35             2.76  0.86
82         1.58                  0.40             1.40             2.20  1.31

     od280/od315_of_diluted_wines  proline  class
115                          2.87    407.0      1
113                          2.31    434.0      1
120                          3.39    625.0      1
110                          2.81    562.0      1
121                          3.69    465.0      1
109                          3.26    680.0      1
94                           2.96    345.0      1
88                           2.75    680.0      1
87                           3.21    562.0      1
75                           2.14    428.0      1
112                          2.50    607.0      1
127                          2.44    466.0      1
96                           2.26    625.0      1
103                          2.44    415.0      1
116                          3.33    495.0      1
84                           3.08    520.0      1
77                           2.52    500.0      1
124                          3.64    380.0      1
74                           3.13    886.0      1
119                          3.05    564.0      1
91                           2.65    450.0      1
80                           3.12    278.0      1
129                          2.57    580.0      1
125                          3.28    378.0      1
82                           2.72    630.0      1
4번 답 :  13.7
     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
115    11.03        1.51  2.20                NaN       85.0           2.46
113    11.41        0.74  2.50               21.0       88.0           2.48
120    11.45        2.40  2.42               20.0       96.0           2.90
110    11.46        3.74  1.82               19.5      107.0           3.18
121    11.56        2.05  3.23               28.5      119.0            NaN
109    11.61        1.35  2.70               20.0       94.0           2.74
94     11.62        1.99  2.28               18.0       98.0           3.02
88     11.64        2.06  2.46               21.6       84.0           1.95
87     11.65        1.67  2.62               26.0       88.0           1.92
75     11.66        1.88  1.92               16.0       97.0           1.61
112    11.76        2.68  2.92               20.0      103.0           1.75
127    11.79        2.13  2.78               28.5       92.0           2.13
96     11.81        2.12  2.74               21.5      134.0           1.60
103    11.82        1.72  1.88               19.5       86.0           2.50
116    11.82        1.47  1.99               20.8       86.0           1.98
84     11.84        0.89  2.58               18.0       94.0           2.20
77     11.84        2.89  2.23               18.0      112.0           1.72
124    11.87        4.31  2.39               21.0       82.0           2.86
74     11.96        1.09  2.30               21.0      101.0           3.38
119    12.00        3.43  2.00               19.0       87.0           2.00
91     12.00        1.51  2.42               22.0       86.0           1.45
80     12.00        0.92  2.00               19.0       86.0           2.42

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
115        2.17                  0.52             2.01             1.90  1.71
113        2.01                  0.42             1.44             3.08  1.10
120        2.79                  0.32             1.83             3.25  0.80
110        2.58                  0.24             3.58             2.90  0.75
121        5.08                  0.47             1.87             6.00  0.93
109        2.92                  0.29             2.49             2.65  0.96
94         2.26                  0.17             1.35             3.25  1.16
88         1.69                  0.48             1.35             2.80  1.00
87         1.61                  0.40             1.34             2.60  1.36
75         1.57                  0.34             1.15             3.80  1.23
112        2.03                  0.60             1.05             3.80  1.23
127        2.24                  0.58             1.76             3.00  0.97
96         0.99                  0.14             1.56             2.50  0.95
103        1.64                  0.37             1.42             2.06  0.94
116        1.60                  0.30             1.53             1.95  0.95
84         2.21                  0.22             2.35             3.05  0.79
77         1.32                  0.43             0.95             2.65  0.96
124        3.03                  0.21             2.91             2.80  0.75
74         2.14                  0.13             1.65             3.21  0.99
119        1.64                  0.37             1.87             1.28  0.93
91         1.25                  0.50             1.63             3.60  1.05
80         2.26                  0.30             1.43             2.50  1.38

     od280/od315_of_diluted_wines  proline  class
115                          2.87    407.0      1
113                          2.31    434.0      1
120                          3.39    625.0      1
110                          2.81    562.0      1
121                          3.69    465.0      1
109                          3.26    680.0      1
94                           2.96    345.0      1
88                           2.75    680.0      1
87                           3.21    562.0      1
75                           2.14    428.0      1
112                          2.50    607.0      1
127                          2.44    466.0      1
96                           2.26    625.0      1
103                          2.44    415.0      1
116                          3.33    495.0      1
84                           3.08    520.0      1
77                           2.52    500.0      1
124                          3.64    380.0      1
74                           3.13    886.0      1
119                          3.05    564.0      1
91                           2.65    450.0      1
80                           3.12    278.0      1
5번 답 :  68.5

In [81]:
data_4 = data2.copy()
data_4['alcohol'].sort_values(ascending=False).head(20)

8      14.83
13     14.75
6      14.39
46     14.38
14     14.38
3      14.37
158    14.34
16     14.30
0      14.23
56     14.22
39     14.22
45     14.21
5      14.20
18     14.19
172    14.16
177    14.13
11     14.12
10     14.10
48     14.10
7      14.06
Name: alcohol, dtype: float64

In [82]:
data_4.sort_values(by='alcohol')

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class
115,11.03,1.51,2.20,NaN,85.0,2.46,2.17,0.52,2.01,1.90,1.71,2.87,407.0,1
113,11.41,0.74,2.50,21.0,88.0,2.48,2.01,0.42,1.44,3.08,1.10,2.31,434.0,1
120,11.45,2.40,2.42,20.0,96.0,2.90,2.79,0.32,1.83,3.25,0.80,3.39,625.0,1
110,11.46,3.74,1.82,19.5,107.0,3.18,2.58,0.24,3.58,2.90,0.75,2.81,562.0,1
121,11.56,2.05,3.23,28.5,119.0,NaN,5.08,0.47,1.87,6.00,0.93,3.69,465.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,14.38,3.59,2.28,16.0,102.0,3.25,3.17,0.27,2.19,4.90,1.04,3.44,1065.0,0
14,14.38,1.87,2.38,12.0,102.0,3.30,3.64,0.29,2.96,7.50,1.20,3.00,1547.0,0
6,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0,0
13,14.75,1.73,2.39,11.4,91.0,3.10,3.69,0.43,2.81,5.40,1.25,2.73,1150.0,0
8,14.83,1.64,2.17,14.0,97.0,2.80,2.98,0.29,1.98,5.20,1.08,2.85,1045.0,0